---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: debian-13-test
    box: debian/trixie64
    memory: 4096
    cpus: 2
    provider_options:
      video_type: "vga"
    # This maps the VM to your playbook's target hosts
    groups:
      - the_host
provisioner:
  name: ansible
  config_options:
    defaults:
      become: true
verifier:
  name: testinfra
  options:
    v: true
    junitxml: "../../infrastructure-report.xml"